import styles from "./Globals.module.css";
import Cabecalho from "@/components/Cabecalho/Cabecalho";
import Rodape from "@/components/Rodape/Rodape";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Agile Modal",
  description: "Generated by Agile Modal",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${styles.container} ${styles.bodyreset}`}>
        <Cabecalho />
        {children}
        <Rodape />
      </body>
    </html>
  );
}
